site_name: InterARTIC Documentation
theme: material
nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Troubleshooting: troubleshooting.md
plugins:
    - search
    - pdf-export